name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-pr-agent:
    runs-on: ubuntu-latest

    container:
      image: anhdt8490/pr-ai-agent:latest
      options: --entrypoint ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PR Agent environment and run
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          config__git_provider: github
          github__token: ${{ secrets.MY_GITHUB_TOKEN }}
          openai__key: ${{ secrets.OPENAI_KEY }}
          openai__api_base: ${{ secrets.OPENAI_API_BASE }}
        run: |
          echo "Running PR Agent on GitHub PR"
          echo "PR_URL=$PR_URL"

          python -m pr_agent.cli --pr_url="$PR_URL" describe --openai.api_base=$openai__api_base
          python -m pr_agent.cli --pr_url="$PR_URL" review -i --openai.api_base=$openai__api_base
          python -m pr_agent.cli --pr_url="$PR_URL" improve --openai.api_base=$openai__api_base
