name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-pr-agent:
    runs-on: self-hosted

    container:
      image: anhdt8490/pr-ai-agent:latest
      options: --entrypoint ""  # Đảm bảo không bị override lệnh mặc định

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> $GITHUB_ENV
          echo "OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }}" >> $GITHUB_ENV

      - name: Run PR Agent
        run: |
          python -m pr_agent.cli --pr_url="$PR_URL" describe
          python -m pr_agent.cli --pr_url="$PR_URL" review -i
          python -m pr_agent.cli --pr_url="$PR_URL" improve
