name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-pr-agent:
    runs-on: ubuntu-latest

    container:
      image: anhdt8490/pr-ai-agent:latest
      options: --entrypoint ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PR Agent environment
        run: |
          echo "Running PR Agent on GitHub PR"
          export PR_URL="${{ github.event.pull_request.html_url }}"
          echo "PR_URL=$PR_URL"
          
          export config__git_provider="github"
          export github__token="${{ secrets.MY_GITHUB_TOKEN }}"   
          export openai__key="${{ secrets.OPENAI_KEY }}"
          export openai__api_base="${{ secrets.OPENAI_API_BASE }}"

          python -m pr_agent.cli --pr_url="$PR_URL" describe --openai.api_base=$openai__api_base
          python -m pr_agent.cli --pr_url="$PR_URL" review -i --openai.api_base=$openai__api_base
          python -m pr_agent.cli --pr_url="$PR_URL" improve --openai.api_base=$openai__api_base
